.TH edfviewer 1 "March 2012" "ESRF" "PyMca X-Ray Fluorescence Toolkit"

.SH NAME

edfviewer - Simple EDF file viewer

.SH SYNOPSIS

edfviewer [FILE(S)]

.SH DESCRIPTION

.P
Tool to visualize image files which format has been wrapped as EDF into 
the X-ray fluorescence toolkit.

Files that can be visualized by this tool include European Synchrotron 
Radiation Facility data format, uncompressed or packbits TIFF, ADSC .img, 
Pilatus .cbf and MarCCD among others.

Consider other tools if you want to do something else than just simple 
visualization: pymca, pymcaroitool or rgbcorrelator should be preferred 
in that case.

.SH SEE ALSO
pymca, pymcaroitool, rgbcorrelator
