.TH elementsinfo 1 "March 2012" "ESRF" "PyMca X-Ray Fluorescence Toolkit"

.SH NAME

elementsinfo - Periodic table with Atomic Constants used by PyMca

.SH SYNOPSIS

elementsinfo

.SH DESCRIPTION

.P
Periodic table displaying the shell constants and X-ray emission branching 
ratios as a function of photon excitation energy used by PyMca.


.SH SEE ALSO
xraylib
