.TH mca2edf 1 "March 2012" "ESRF" "PyMca X-Ray Fluorescence Toolkit"

.SH NAME

mca2edf - Convert SPEC file format files to EDF format

.SH SYNOPSIS

mca2edf [OPTIONS] [FILES]

.SH DESCRIPTION

.P
X-ray maps were stored at the European Synchrotron Radiation 
Facility as a set of images in ESRF Data Format (EDF). The 
image rows being associated to points of a horizontal sample 
scan and the image columns to the spectrum channels. 

This tool allows one to convert a set of files wrapped by the 
PyMca Toolkit as SPEC file format, and therefore without sample 
position information, to European Synchrotron Radiation 
Facility data format (EDF).

Its usefulness is nowdays somehow limited because recent PyMca 
developements allow to reshape nspectra x nchannels datasets in 
the tools making use of the shape information (pymcaroitool, 
pymcapostbatch).

.SH EXAMPLES

.B  mca2edf
    Open a dialog to select input files, output directory and the
    number of spectra on each horizontal row.
    
.B  mca2edf --outdir=/tmp --mcastep=2 *.mca
    Convert all the .mca files in current directory to a set of EDF 
    files containing two spectra. The output is placed in /tmp 

.B  mca2edf --outdir=/tmp --mcastep=2 --listfile=input_file
    Same as before but applied to all the files listed in input_file.
    Each line of input_file must contain a valid file name.
    
.SH SEE ALSO
pymcaroitool, pymcapostbatch
