#!python

import os
import sys
import PyMca5.PyMcaGui.physics.xrf as target

fname = os.path.join(os.path.dirname(target.__file__), 'ElementsInfo.py')
if sys.version < '3.0':
    execfile(fname)
else:
    f = open(fname, "rb")
    code_txt = f.read()
    f.close()
    if sys.version_info < (3, 6):
        code = compile(code_txt, fname, 'exec')
    else:
        code = code_txt
    exec(code)
