#!python

import os
import sys
import PyMca5.PyMcaGui.pymca as target

fname = os.path.join(os.path.dirname(target.__file__), 'PyMcaBatch.py')
if sys.version < '3.0':
    execfile(fname)
else:
    f = open(fname, "rb")
    code = f.read()
    f.close()
    exec(code)
