#!python

import os
import sys
from PyMca5.PyMcaGui.pymca import QStackWidget as target

fname = os.path.join(os.path.dirname(target.__file__), 'QStackWidget.py')
if sys.version < '3.0':
    execfile(fname)
else:
    exec(compile(open(fname).read(), fname, 'exec'))
