#!python

import os
import sys
import PyMca5.PyMcaGui.pymca.PyMcaPostBatch as target

fname = os.path.join(os.path.dirname(target.__file__), 'PyMcaPostBatch.py')
if sys.version < '3.0':
    execfile(fname)
else:
    exec(compile(open(fname).read(), fname, 'exec'))
